---
title: "M MSE"
author: "Laurence Kell"
date: "21/07/2014"
output: pdf_document
---
  
```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, 
               fig.width =6, 
               fig.height=6,
               fig.path  ="tex/mse",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE, 
               eval   =TRUE,
               cache  =TRUE)
iFig=0
```

```{r init}
library(FLCore)
library(FLash)
library(FLBRP)
library(ggplotFL)
library(FLXSA)
library(FLife)
library(mpb)
library(plyr)

source('~/Desktop/flr/mse/R/msy.R')
source('~/Desktop/flr/mse/R/hcr.R')
source('~/Desktop/flr/mse/R/mseXSA.R')
source('~/Desktop/flr/mse/R/mseEMP.R')
```

```{r OM}
##Use Life history to generate a stock
data(teleost)

alb=lhPar(teleost[,"Thunnus alalunga"])
alb["sl"]=1

nits=100
mFn<-function(age,...) FLQuant(0.2,dimnames=dimnames(age))

##OM
eql=lhEql(alb, range=c(min=0,max=10,plusgroup=10,minfbar=5,maxfbar=9))
fbar(eql)=FLBRP:::refpts(eql)["msy","harvest"]*FLQuant(c(rep(.1,19),
                                                         seq(.1,2,length.out=40),
                                                         seq(2,.7,length.out=11)[-1],
                                                         rep(.7,61)))
set.seed(1233)
srDev=FLife:::rlnoise(nits,fbar(eql)[,-1,,,,1]*0,.3,b=0.0)
set.seed(1233)
srDev6=FLife:::rlnoise(nits,fbar(eql)[,-1,,,,1]*0,.3,b=0.5)
set.seed(3321)
uDev =rlnorm(nits,setPlusGroup(stock.n(eql),10)*0,.2)

save(eql,  file="/home/laurie/Desktop/flr/FLRP/data/eql.RData",  compress="xz")
save(srDev,file="/home/laurie/Desktop/flr/FLRP/data/srDev.RData",compress="xz")
save(uDev, file="/home/laurie/Desktop/flr/FLRP/data/uDev.RData", compress="xz")

om =propagate(fwd(eql),nits)
oms=FLStocks("Perfect"=fwd(om,f=fbar(om)[,-1],sr.residuals=rlnorm(nits,fbar(om)[,-1,,,,1]*0,.3),sr=eql))
```

```{r xsa}
rf=lhEql(alb,range=c(min=0,max=10,plusgroup=10,minfbar=5,maxfbar=9))
mp=window(setPlusGroup(oms[["Perfect"]],10),end=90)

##Assessment
control=FLXSA.control(tol    =1e-09,maxit=50, 
                      min.nse=0.3,  fse  =0.1, 
                      rage=0,       qage =10, 
                      shk.n=TRUE,   shk.f   =TRUE, 
                      shk.yrs=4,    shk.ages=5, 
                      window=100,   tsrange =10, 
                      tspower=0,
                      vpa=FALSE)

idx=FLIndex(index=stock.n(mp)%*%uDev[,dimnames(stock.n(mp))$year])
range(idx)[c("plusgroup","startf","endf")]=c(NA,0.1,.2)

xsa=FLXSA(mp,idx,
          control=control,diag.flag=FALSE)
range(xsa)[c("min","max","plusgroup")]=range(mp)[c("min","max","plusgroup")]
mp=mp+xsa
  
p=plot(FLStocks(mp=mp,om=window(oms[["Perfect"]],end=90)))
```

```{r perfect-noise}
set.seed(6778)
oms[["Perfect Noise in M"]]=oms[["Perfect"]]
m(oms[["Perfect Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.0,what="year")

oms[["Perfect Noise in M"]]=fwd(oms[["Perfect Noise in M"]],
                                      f=fbar(oms[["Perfect"]])[,-1],sr=eql,
                                      sr.residuals=srDev)
```

```{r perfect-red-noise}
set.seed(6778)
oms[["Perfect Red Noise in M"]]=oms[["Perfect"]]
m(oms[["Perfect Red Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.5,what="year")

oms[["Perfect Red Noise in M"]]=fwd(oms[["Perfect Red Noise in M"]],
                                      f=fbar(oms[["Perfect"]])[,-1],sr=eql,
                                      sr.residuals=srDev)
```

```{r whitebox1}
source('~/Desktop/flr/mse/R/mseXSA.R')

oms[["White Box"]]=mseXSA(oms[["Perfect"]],
                          eql,mp,rf,control,srDev=srDev,uDev=uDev,start=75,end=100)
```

```{r whitebox2}
source('~/Desktop/flr/mse/R/mseXSA.R')

##Noise in M
oms[["White Box Noise in M"]]=mseXSA(oms[["Perfect Noise in M"]],
                                     eql,mp,rf,control,srDev=srDev,uDev=uDev,start=75,end=100)
```

```{r whitebox3}
source('~/Desktop/flr/mse/R/mseXSA.R')

##Red noise in M
source('~/Desktop/flr/mse/R/mseXSA.R')

oms[["White Box Red Noise in M"]]=mseXSA(oms[["Perfect Red Noise in M"]],
                               eql,mp,rf,control,srDev=srDev,uDev=uDev,start=75,end=100)
```

```{r check}
mp=setPlusGroup(window(om,end=100),10)
idx=FLIndex(index=stock.n(mp)[-11])
range(idx)[c("startf","endf")]=c(0.5,0.6)
plot(FLStocks(mp=mp,om=window(om,end=100)))
  
xsa=FLXSA(mp,idx,
            control=control,
            diag.flag=FALSE)
range(xsa)[c("min","max","plusgroup")]=range(mp)[c("min","max","plusgroup")]
  
i=seq(nits)
plot(FLStocks(mp=iter(mp+xsa,i),om=iter(window(om,end=100),i)))
```
**Figure `r iFig=iFig+1; iFig`**

```{r blackbox1}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")
load("/home/laurie/Desktop/flr/FLRP/data/eql.RData")
load("/home/laurie/Desktop/flr/FLRP/data/srDev.RData")
load("/home/laurie/Desktop/flr/FLRP/data/uDev.RData")

source('~/Desktop/flr/mse/R/mseEMP.R')

oms[["Black Box"]]=mseEMP(oms[["Perfect"]],eql,srDev=srDev,uDev=uDev,start=75,end=100)
```

```{r blackbox2}
oms[["Black Box Noise in M"]]=mseEMP(oms[["Perfect Noise in M"]],
                               eql,srDev=srDev,uDev=uDev,start=75,end=100)
```

```{r blackbox3}
oms[["Black Box Red Noise in M"]]=mseEMP(oms[["Perfect Red Noise in M"]],
                                   eql,srDev=srDev,uDev=uDev,start=75,end=100)

save(oms,file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r greybox}
source('~/Desktop/flr/mse/R/mseMPB.R')

source('~/Desktop/flr/mpb/R/biodyn-fit.R')
library(stringr)

load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")
load("/home/laurie/Desktop/flr/FLRP/data/eql.RData")
load("/home/laurie/Desktop/flr/FLRP/data/uDev.RData")
load("/home/laurie/Desktop/flr/FLRP/data/srDev.RData")

set.seed(1233)
srDev=FLife:::rlnoise(nits,fbar(eql)[,-1,,,,1]*0,.3,b=0.5)

## Set up MP
om=window(oms[["Perfect"]],start=20,end=75)
mp=window(as(window(om,end=75),"biodyn"),start=20,end=75)
mp@indices=FLQuants("1"=window(catch(om)%/%fbar(om),start=20,end=75-1))

params(    mp)["r"]=.3
mp=fwd(    mp,catch=catch(mp))
setParams( mp)=mp@indices[[1]]

setControl(mp)=params(mp)
control(   mp)["r",2:4]=c(.1,.3,0.6)
mp=fit(    mp)

setControl(mp)=params(mp)
control(   mp)["r",2:4]=c(.1,.3,0.6)
#mp@priors["r",c("weight","a")]=c(1000,0.3)
```

```{r greybox1}
##Grey Box
source('~/Desktop/flr/mse/R/mseMPB.R')
oms[["Grey Box"]]=
  mseMPB(window(oms[["Perfect"]],start=20,end=110),eql,mp,srDev=srDev,uDev=uDev,start=75,end=103)
save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r greybox2}
##Grey Box Noise in M
oms[["Grey Box Noise in M"]]=
  mseMPB(window(oms[["Perfect Noise in M"]],start=20,end=110),eql,mp,srDev=srDev,uDev=uDev,start=75,end=102)
save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r greybox3}
##Grey Box Red Noise in M
oms[["Grey Box Red Noise in M"]]=
  mseMPB(window(oms[["Perfect Red Noise in M"]],start=20,end=110),eql,mp,srDev=srDev,uDev=uDev,start=75,end=103)
save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r greybox1-ar}
oms[["Grey Box AR"]]=fwd(oms[["Perfect"]],
                                      f=fbar(oms[["Perfect"]])[,-1],sr=eql,
                                      sr.residuals=srDev6)

##Grey Box
source('~/Desktop/flr/mse/R/mseMPB.R')
oms[["Grey Box AR"]]=
  mseMPB(window(oms[["Grey Box AR"]],start=20,end=110),eql,mp,srDev=srDev6,uDev=uDev,start=75,end=103)
save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r greybox2-ar}
##Grey Box Noise in M
oms[["Grey Box Noise in M AR"]]=fwd(oms[["Perfect Noise in M"]],
                                      f=fbar(oms[["Perfect Noise in M"]])[,-1],sr=eql,
                                      sr.residuals=srDev6)
oms[["Grey Box Noise in M AR"]]=
  mseMPB(window(oms[["Perfect Noise in M"]],start=20,end=110),eql,mp,srDev=srDev6,uDev=uDev,start=75,end=102)
save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r greybox3-ar}
##Grey Box Noise in M
oms[["Grey Box  Red Noise in M AR"]]=fwd(oms[["Perfect Red Noise in M"]],
                                      f=fbar(oms[["Perfect Red Noise in M"]])[,-1],sr=eql,
                                      sr.residuals=srDev6)

oms[["Grey Box Red Noise in M AR"]]=
  mseMPB(window(oms[["Perfect Noise in M"]],start=20,end=110),eql,mp,srDev=srDev6,uDev=uDev,start=75,end=102)
save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r summary-ssb}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

dat=transform(ldply(oms[-c(13:15)],function(x) 
  as.data.frame(window(ssb(x),start=75,end=100),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","White Box Noise in M","White Box Red Noise in M",
                                 "Grey Box","Grey Box Noise in M","Grey Box Red Noise in M",
                                 "Grey Box AR","Grey Box Noise in M AR","Grey Box Red Noise in M AR",
                                 "Black Box","Black Box Noise in M","Black Box Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))
dat2=ddply(dat,.(year,Scenario), with, quantile(data,probs=c(0.25,0.5,0.75)))


ggplot()+
  geom_line(aes(year,data,group=iter),alpha=.1,data=subset(dat,as.numeric(iter)<=50))+
  geom_vline(xintercept=91,col="black")+
  geom_line(aes(year,data,group=iter),alpha=.25,data=subset(dat,as.numeric(iter) >50))+
  geom_line(aes(year,`50%`),data=dat2,col="grey100",size=1.0)+
  geom_line(aes(year,`25%`),data=dat2,col="grey100",size=0.5)+
  geom_line(aes(year,`75%`),data=dat2,col="grey100",size=0.5)+
  facet_wrap(~Scenario,ncol=3)+
  theme_bw()+
  theme(legend.position="none")+
  xlab("Year")+ylab("SSB")
```

**Figure `r iFig=iFig+1; iFig`**

```{r summary-F}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

dat=transform(ldply(oms[-c(13:15)],function(x) as.data.frame(window(fbar(x),start=75,end=100),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","White Box Noise in M","White Box Red Noise in M",
                                 "Grey Box","Grey Box Noise in M","Grey Box Red Noise in M",
                                 "Grey Box AR","Grey Box Noise in M AR","Grey Box Red Noise in M AR",
                                 "Black Box","Black Box Noise in M","Black Box Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))
dat2=ddply(dat,.(year,Scenario), with, quantile(data,probs=c(0.25,0.5,0.75)))


ggplot()+
  geom_line(aes(year,data,group=iter),alpha=.1,data=subset(dat,as.numeric(iter)<=50))+
  geom_vline(xintercept=91,col="black")+
  geom_line(aes(year,data,group=iter),alpha=.25,data=subset(dat,as.numeric(iter) >50))+
  geom_line(aes(year,`50%`),data=dat2,col="grey100",size=1.0)+
  geom_line(aes(year,`25%`),data=dat2,col="grey100",size=0.5)+
  geom_line(aes(year,`75%`),data=dat2,col="grey100",size=0.5)+
  facet_wrap(~Scenario,ncol=3)+
  theme_bw()+
  theme(legend.position="none")+
  xlab("Year")+ylab("F")+
  scale_y_continuous(limits=c(0,0.5))
```

**Figure `r iFig=iFig+1; iFig`**

```{r summary-yield}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

dat=transform(ldply(oms[-c(13:15)],function(x) as.data.frame(window(catch(x),start=75,end=100),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","White Box Noise in M","White Box Red Noise in M",
                                 "Grey Box","Grey Box Noise in M","Grey Box Red Noise in M",
                                 "Grey Box AR","Grey Box Noise in M AR","Grey Box Red Noise in M AR",
                                 "Black Box","Black Box Noise in M","Black Box Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))
dat2=ddply(dat,.(year,Scenario), with, quantile(data,probs=c(0.25,0.5,0.75)))


ggplot()+
  geom_line(aes(year,data,group=iter),alpha=.1,data=subset(dat,as.numeric(iter)<=50))+
  geom_vline(xintercept=91,col="black")+
  geom_line(aes(year,data,group=iter),alpha=.25,data=subset(dat,as.numeric(iter) >50))+
  geom_line(aes(year,`50%`),data=dat2,col="grey100",size=1.0)+
  geom_line(aes(year,`25%`),data=dat2,col="grey100",size=0.5)+
  geom_line(aes(year,`75%`),data=dat2,col="grey100",size=0.5)+
  facet_wrap(~Scenario,ncol=3)+
  theme_bw()+
  theme(legend.position="none")+
  xlab("Year")+ylab("Yield")+
  scale_y_continuous(limits=c(0,200))
```

**Figure `r iFig=iFig+1; iFig`**

```{r spectra}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

dat=transform(ldply(oms[-c(13-15)],function(x) as.data.frame(window(catch(x),start=75,end=100),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","White Box Noise in M","White Box Red Noise in M",
                                 "Grey Box","Grey Box Noise in M","Grey Box Red Noise in M",
                                 "Grey Box AR","Grey Box Noise in M AR","Grey Box Red Noise in M AR",
                                 "Black Box","Black Box Noise in M","Black Box Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))
spc=ddply(dat,.(Scenario,.id,iter), with, 
          FLife:::spectra(as.FLQuant(data.frame(data=data,year=year))))


ggplot(subset(spc,f<0.1))+
  geom_boxplot(aes(factor(f),mx))+
  facet_wrap(~.id,ncol=3,scale="free")
```

**Figure `r iFig=iFig+1; iFig`**

```{r}
f=fbar(oms[["Perfect"]])[,-1]
f[]=eql@refpts["msy","harvest"]

oms[["Ref"]]=fwd(oms[["Perfect"]],f=f,sr=eql,sr.residuals=srDev)
oms[["Ref Noise in M"]]=fwd(oms[["Perfect Noise in M"]],f=f,sr=eql,sr.residuals=srDev)
oms[["Ref Red Noise in M"]]=fwd(oms[["Perfect Red Noise in M"]],f=f,sr=eql,sr.residuals=srDev)

save(oms, file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

plot(FLStocks(llply(oms[sort(names(oms))[seq(1,18,3)]],function(x) x[,ac(75:100)])))
```

**Figure `r iFig=iFig+1; iFig`**

```{r}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

plot(FLStocks(llply(oms[sort(names(oms))[seq(2,18,3)]],function(x) x[,ac(75:100)])))
```

**Figure `r iFig=iFig+1; iFig`**

```{r}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")

plot(FLStocks(llply(oms[sort(names(oms))[seq(3,18,3)]],function(x) x[,ac(75:100)])))
```

**Figure `r iFig=iFig+1; iFig`**

```{r,eval=FALSE}
load("/home/laurie/Desktop/flr/FLRP/data/oms.RData")
load("/home/laurie/Desktop/flr/FLRP/data/eql.RData")

ssbFn<-function(x,rfs=eql@refpts["msy"]) ssb(x)%/%rfs[,"ssb"]
fbrFn<-function(x,rfs=eql@refpts["msy"]) fbar(x)%/%rfs[,"harvest"]
yldFn<-function(x,rfs=eql@refpts["msy"]) catch(x)%/%rfs[,"yield"]
recFn<-function(x,rfs=eql@refpts["msy"]) catch(x)%/%rfs[,"recruits"]

ss=ldply(oms,function(x) as.data.frame(FLQuants(x[,ac(76:100)],
                                                "ssb"=ssbFn,
                                                "fbr"=fbrFn,
                                                "yld"=yldFn),drop=TRUE))
save("ss",file="/home/laurie/Desktop/flr/FLRP/data/ss.RData", compress="xz")
```

```{r}
load("/home/laurie/Desktop/flr/FLRP/data/ss.RData")

key=data.frame(
  .id=c("Perfect",    "Perfect Noise in M",       "Perfect Red Noise in M",  
        "White Box",  "White Box Noise in M",     "White Box Red Noise in M",
        "Grey Box",   "Grey Box Noise in M",      "Grey Box Red Noise in M",  
        "Grey Box AR", "Grey Box Noise in M AR",  "Grey Box Red Noise in M AR",  
        "Black Box",  "Black Box Noise in M",     "Black Box Red Noise in M",
        "Ref",        "Ref Noise in M",           "Ref Red Noise in M"),
  mp=rep(c("Perfect","White Box","Grey Box","Grey Box AR","Black Box","Ref"),each=3),
  om=rep(c("None","Noise","Red Noise"),6),stringsAsFactors=FALSE)

ss.=transform(merge(ss,key,by=".id"),om=factor(om,levels=c("None","Noise","Red Noise")))

ggplot(subset(ss.,qname=="ssb"&mp%in%c("White Box","Grey Box","Grey Box AR","Black Box")))+
  geom_boxplot(aes(factor(year),data))+
  facet_grid(mp~om)
```

**Figure `r iFig=iFig+1; iFig`**

```{r}
ggplot(ddply(subset(ss.,qname=="ssb"&mp%in%c("White Box","Grey Box","Grey Box AR","Black Box")),
          .(mp,om,year), with, data.frame(p=mean(ifelse(data>=1,1,0)))))+
  geom_line(aes(year,p,col=mp))+
  facet_grid(om~.)
```

**Figure `r iFig=iFig+1; iFig`**

```{r}
ggplot(ddply(subset(ss.,qname=="fbr"&mp%in%c("White Box","Grey Box","Grey Box AR","Black Box")&year<=90),
          .(mp,om,year), with, data.frame(p=median(data))))+
 geom_line(aes(year,p,col=mp))+
  facet_grid(om~.)

```

**Figure `r iFig=iFig+1; iFig`** Median SSB

```{r}
ggplot(ddply(subset(ss.,qname=="yld"&mp%in%c("White Box","Grey Box","Grey Box AR","Black Box")&year<=90),
          .(mp,om,year), with, data.frame(p=median(data))))+
 geom_line(aes(year,p,col=mp))+
  facet_grid(om~.)

```

**Figure `r iFig=iFig+1; iFig`** Median Yield.
