---
title: "M MSE"
author: "Laurence Kell"
date: "21/07/2014"
output: html_document
---
  
```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, 
               fig.width =6, 
               fig.height=6,
               fig.path  ="tex/mse",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE, 
               eval   =TRUE,
               cache  =TRUE)
iFig=0
```

```{r init}
library(FLCore)
library(FLash)
library(FLBRP)
library(ggplotFL)
library(FLXSA)
library(FLife)
library(mpb)
library(plyr)

source('~/Desktop/flr/mse/R/msy.R')
source('~/Desktop/flr/mse/R/hcr.R')
source('~/Desktop/flr/mse/R/mseXSA.R')
source('~/Desktop/flr/mse/R/mseEMP.R')
```

```{r OM}
##Use Life history to generate a stock
data(teleost)

alb=lhPar(teleost[,"Thunnus alalunga"])
alb["sl"]=1

nits=100
mFn<-function(age,...) FLQuant(0.2,dimnames=dimnames(age))

##OM
eql=lhEql(alb, range=c(min=0,max=10,plusgroup=10,minfbar=5,maxfbar=9))
fbar(eql)=FLBRP:::refpts(eql)["msy","harvest"]*FLQuant(c(rep(.1,19),
                                                         seq(.1,2,length.out=40),
                                                         seq(2,.7,length.out=11)[-1],
                                                         rep(.7,61)))

save(eql,file="/home/laurie/Desktop/flr/FLRP/data/eql.RData")

srDev=rlnorm(nits,fbar(eql)[,-1,,,,1]*0,.3)
om =propagate(fwd(eql),nits)
oms=FLStocks("Perfect"=fwd(om,f=fbar(om)[,-1],sr.residuals=rlnorm(nits,fbar(om)[,-1,,,,1]*0,.3),sr=eql))
```

```{r mp}
rf=lhEql(alb,range=c(min=0,max=10,plusgroup=10,minfbar=5,maxfbar=9))
mp=window(setPlusGroup(oms[["Perfect"]],10),end=90)

##Assessment
control=FLXSA.control(tol    =1e-09,maxit=50, 
                      min.nse=0.3,  fse  =0.1, 
                      rage=0,       qage =10, 
                      shk.n=TRUE,   shk.f   =TRUE, 
                      shk.yrs=10,   shk.ages=5, 
                      window=100,   tsrange =10, 
                      tspower=0,
                      vpa=FALSE)
```

```{r oem}
uDev=rlnorm(nits,setPlusGroup(stock.n(oms[["Perfect"]]),10)[-11,,,,,1]*0,.2)
idx=FLIndex(index=stock.n(mp)[-11]%*%uDev[,dimnames(stock.n(mp))$year])
range(idx)[c("plusgroup","startf","endf")]=c(NA,0.1,.2)
```

```{r sa}
xsa=FLXSA(mp,idx,
          control=control,diag.flag=FALSE)
range(xsa)[c("min","max","plusgroup")]=range(mp)[c("min","max","plusgroup")]
mp=mp+xsa
  
plot(FLStocks(mp=mp,om=window(oms[["Perfect"]],end=90)))
```

```{r sa-noise}
oms[["Perfect Noise in M"]]=oms[["Perfect"]]
m(oms[["Perfect Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.0,what="year")

oms[["Perfect Noise in M"]]=fwd(oms[["Perfect Noise in M"]],
                                      f=fbar(oms[["Perfect"]])[,-1],sr=eql,
                                      sr.residuals=rlnorm(nits,fbar(oms[["Perfect"]])[,-1,,,,1]*0,.3))
```

```{r sa-red-noise}
oms[["Perfect Red Noise in M"]]=oms[["Perfect"]]
m(oms[["Perfect Red Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.5,what="year")

oms[["Perfect Red Noise in M"]]=fwd(oms[["Perfect Red Noise in M"]],
                                      f=fbar(oms[["Perfect"]])[,-1],sr=eql,
                                      sr.residuals=rlnorm(nits,fbar(oms[["Perfect"]])[,-1,,,,1]*0,.3))
```

```{r mse1}
##Runs
oms[["White Box"]]=mseXSA(oms[["Perfect"]],eql,mp,rf,control,srDev=srDev,uDev=uDev,start=90,end=128)
```

```{r mse2}
##Noise in M
oms[["Noise in M"]]=oms[["Perfect"]]
m(oms[["Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.0,what="year")
oms[["Noise in M"]]=fwd(oms[["Noise in M"]],f=fbar(oms[["Perfect"]])[,-1],
                                            sr.residuals=srDev,sr=eql)
oms[["Noise in M"]]=mseXSA(oms[["Noise in M"]],eql,mp,rf,control,srDev=srDev,uDev=uDev,start=90,end=128)
```

```{r mse3}
##Red noise in M
oms[["Red Noise in M"]]=oms[["Perfect"]]
m(oms[["Red Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.5,what="year")
oms[["Red Noise in M"]]=fwd(oms[["Red Noise in M"]],f=fbar(oms[["Perfect"]])[,-1],
                                                    sr.residuals=srDev,sr=eql)
oms[["Red Noise in M"]]=mseXSA(oms[["Red Noise in M"]],
                               eql,mp,rf,control,srDev=srDev,uDev=uDev,start=90,end=128)
```

```{r check, eval=FALSE}
  mp=setPlusGroup(window(om,end=100),10)
  idx=FLIndex(index=stock.n(mp)[-11])
  range(idx)[c("startf","endf")]=c(0.5,0.6)
  plot(FLStocks(mp=mp,om=window(om,end=100)))
  
  xsa=FLXSA(mp,idx,
            control=control,
            diag.flag=FALSE)
  range(xsa)[c("min","max","plusgroup")]=range(mp)[c("min","max","plusgroup")]
  
  i=seq(nits)
  print(plot(FLStocks(mp=iter(mp+xsa,i),om=iter(window(om,end=100),i))))
```

```{r mse-white1}
source('~/Desktop/flr/mse/R/mseEMP.R')
uDev=rlnorm(nits,stock.n(oms[["Perfect"]])[,,,,,1]*0,.2)

oms[["EMP"]]=mseEMP(oms[["Perfect"]],eql,srDev=srDev,uDev=uDev,start=90,end=128)
```

```{r mse-Noise}
source('~/Desktop/flr/mse/R/mseEMP.R')

oms[["EMP Noise in M"]]=oms[["Perfect"]]
m(oms[["EMP Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.0,what="year")
oms[["EMP Noise in M"]]=fwd(oms[["EMP Noise in M"]],f=fbar(oms[["Perfect"]])[,-1],
                                            sr.residuals=srDev,sr=eql)

oms[["EMP Noise in M"]]=mseEMP(oms[["EMP Noise in M"]],eql,srDev=srDev,uDev=uDev,start=90,end=128)
```

```{r mse-emp3}
source('~/Desktop/flr/mse/R/mseEMP.R')

##Red noise in M
oms[["EMP Red Noise in M"]]=oms[["Perfect"]]
m(oms[["EMP Red Noise in M"]])=FLife:::rlnoise(nits,log(m(oms[["Perfect"]])),0.2,0.5,what="year")
oms[["EMP Red Noise in M"]]=fwd(oms[["EMP Red Noise in M"]],f=fbar(oms[["Perfect"]])[,-1],
                                                    sr.residuals=srDev,sr=eql)

oms[["EMP Red Noise in M"]]=mseEMP(oms[["EMP Red Noise in M"]],eql,srDev=srDev,uDev=uDev,start=90,end=128)
```

```{r save}
save(oms,file="/home/laurie/Desktop/flr/FLRP/data/oms.RData")
```

```{r summary, eval=FALSE}
source('~/Desktop/flr/mse/R/mseMPB.R')
uDev=rlnorm(nits,stock.n(oms[["Perfect"]])[,,,,,1]*0,.2)

oms[["MPB"]]=mseMPB(oms[["Perfect"]],eql,srDev=srDev,uDev=uDev,start=90,end=128)
```


```{r summary-ssb}
dat=transform(ldply(oms,function(x) as.data.frame(window(ssb(x),start=85,end=120),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","Noise in M","Red Noise in M",
                                 "EMP","EMP Noise in M","EMP Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))
dat2=ddply(dat,.(year,Scenario), with, quantile(data,probs=c(0.25,0.5,0.75)))

ggplot()+
  geom_line(aes(year,data,group=iter),alpha=.1,data=subset(dat,as.numeric(iter)<=50))+
  geom_vline(xintercept=91,col="black")+
  geom_line(aes(year,data,group=iter),alpha=.25,data=subset(dat,as.numeric(iter) >50))+
  geom_line(aes(year,`50%`),data=dat2,col="grey100",size=1.0)+
  geom_line(aes(year,`25%`),data=dat2,col="grey100",size=0.5)+
  geom_line(aes(year,`75%`),data=dat2,col="grey100",size=0.5)+
  facet_wrap(~Scenario)+
  theme_bw()+
  theme(legend.position="none")+
  xlab("Year")+ylab("SSB")
```


```{r summary-F}
dat=transform(ldply(oms,function(x) as.data.frame(window(fbar(x),start=85,end=120),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","Noise in M","Red Noise in M",
                                 "EMP","EMP Noise in M","EMP Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))

dat2=ddply(dat,.(year,Scenario), with, quantile(data,probs=c(0.25,0.5,0.75)))
ggplot()+
  geom_line(aes(year,data,group=iter),alpha=.1,data=subset(dat,as.numeric(iter)<=50))+
  geom_vline(xintercept=91,col="black")+
  geom_line(aes(year,data,group=iter),alpha=.25,data=subset(dat,as.numeric(iter) >50))+
  geom_line(aes(year,`50%`),data=dat2,col="grey100",size=1.0)+
  geom_line(aes(year,`25%`),data=dat2,col="grey100",size=0.5)+
  geom_line(aes(year,`75%`),data=dat2,col="grey100",size=0.5)+
  facet_wrap(~Scenario)+
  theme_bw()+
  theme(legend.position="none")+
  xlab("Year")+ylab("F")+
  scale_y_continuous(limits=c(0,0.5))
```


```{r summary-yield}
dat=transform(ldply(oms,function(x) as.data.frame(window(catch(x),start=85,end=120),drop=TRUE)),
    Scenario=factor(.id,levels=c("White Box","Noise in M","Red Noise in M",
                                 "EMP","EMP Noise in M","EMP Red Noise in M",
                                 "Perfect","Perfect Noise in M","Perfect Red Noise in M")))
dat2=ddply(dat,.(year,Scenario), with, quantile(data,probs=c(0.25,0.5,0.75)))


ggplot()+
  geom_line(aes(year,data,group=iter),alpha=.1,data=subset(dat,as.numeric(iter)<=50))+
  geom_vline(xintercept=91,col="black")+
  geom_line(aes(year,data,group=iter),alpha=.25,data=subset(dat,as.numeric(iter) >50))+
  geom_line(aes(year,`50%`),data=dat2,col="grey100",size=1.0)+
  geom_line(aes(year,`25%`),data=dat2,col="grey100",size=0.5)+
  geom_line(aes(year,`75%`),data=dat2,col="grey100",size=0.5)+
  facet_wrap(~Scenario)+
  theme_bw()+
  theme(legend.position="none")+
  xlab("Year")+ylab("Yield")+
  scale_y_continuous(limits=c(0,200))
```


```{r summary3}
ggplot(dat)+
  geom_boxplot(aes(factor(year),data))+
  facet_wrap(~Scenario)+
    theme_bw()+theme(legend.position="none")
```
