# sa.R - Status and trend estimators and indicators.
# mse/R/sa.R

# Copyright European Union, 2018-2021
# Author: Iago Mosqueira (EC JRC) <iago.mosqueira@ec.europa.eu>
#
# Distributed under the terms of the European Union Public Licence (EUPL) V.1.1.

# perfect.sa {{{


#' A perfect 'estimate' of abundances, catches and harvest.
#'
#' The *FLStock* generated by the call to *oem* is simply passed on in this
#' function. The estimates of abundance, catches and exploitation will thus be
#' as precise as the OEM observation.
#'
#' @param stk The stock observation generated by *oem*. Class *FLStock*.
#' @param idx An observation of chnages in abundance, not used. Class *FLIndices*.
#' @param args MSE arguments, class *list*.
#' @param tracking Structure for tracking modules outputs.
#'
#' @return A *list* with elements *stk* and *tracking*.
#'
#' @examples
#' # Example dataset
#' data(sol274)
#' 
#' # Sets up an mpCtrl for catch ~ MSY
#' ctrl <- mpCtrl(est = mseCtrl(method=perfect.sa),
#'   hcr = mseCtrl(method=fixedC.hcr, args=list(ctrg=11400)))
#' 
#' # Runs mp between 2021 and 2035
#' run <- mp(om, control=ctrl, args=list(iy=2021, fy=2035))

perfect.sa <- function(stk, idx, args, tracking, ...) {
 
  dy <- args$dy
  ay <- args$ay

  stk <- window(stk, end=dy)

  if(all(is.na(harvest(stk))))
    harvest(stk) <- harvest(stock.n(stk), catch.n(stk), m(stk))
  
  track(tracking, "conv.est", ac(ay)) <- 1
  
  list(stk=stk, tracking=tracking)
}
# }}}
